-- MySQL Script generated by MySQL Workbench
-- Sun Nov 20 11:17:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Apostador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Apostador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Apostador` (
  `idUtilizador` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` NVARCHAR(10) NOT NULL,
  `NIF` INT NOT NULL,
  `saldo` DECIMAL(7,2) NULL DEFAULT 0,
  `amigos` INT NOT NULL,
  PRIMARY KEY (`idUtilizador`),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) VISIBLE,
  INDEX `fk_Apostador_Apostador1_idx` (`amigos` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_Apostador_Apostador1`
    FOREIGN KEY (`amigos`)
    REFERENCES `mydb`.`Apostador` (`idUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Participante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Participante` (
  `idParticipante` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idParticipante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Promoção`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Promoção` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Promoção` (
  `idPromoções` INT NOT NULL,
  `ValorPromoção` DECIMAL(4,3) NOT NULL,
  `DataInicial` DATE NOT NULL,
  `DataFinal` DATE NOT NULL,
  PRIMARY KEY (`idPromoções`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admnistrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Admnistrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Admnistrador` (
  `username` VARCHAR(16) NOT NULL,
  `idEspecialista` INT NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `Promoções_idPromoções` INT NOT NULL,
  PRIMARY KEY (`idEspecialista`),
  INDEX `fk_Admnistrador_Promoções1_idx` (`Promoções_idPromoções` ASC) VISIBLE,
  CONSTRAINT `fk_Admnistrador_Promoções1`
    FOREIGN KEY (`Promoções_idPromoções`)
    REFERENCES `mydb`.`Promoção` (`idPromoções`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Modalidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Modalidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Modalidade` (
  `nome` VARCHAR(45) NOT NULL,
  `ícone` VARCHAR(100) NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EventoDesportivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EventoDesportivo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EventoDesportivo` (
  `idEventoDesportivo` INT NOT NULL,
  `Data` DATETIME NULL,
  `Participante_idParticipante` INT NOT NULL,
  `Admnistrador_idEspecialista` INT NOT NULL,
  `Modalidade_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEventoDesportivo`),
  INDEX `fk_EventoDesportivo_Participante1_idx` (`Participante_idParticipante` ASC) VISIBLE,
  INDEX `fk_EventoDesportivo_Admnistrador1_idx` (`Admnistrador_idEspecialista` ASC) VISIBLE,
  INDEX `fk_EventoDesportivo_Modalidade1_idx` (`Modalidade_nome` ASC) VISIBLE,
  CONSTRAINT `fk_EventoDesportivo_Participante1`
    FOREIGN KEY (`Participante_idParticipante`)
    REFERENCES `mydb`.`Participante` (`idParticipante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EventoDesportivo_Admnistrador1`
    FOREIGN KEY (`Admnistrador_idEspecialista`)
    REFERENCES `mydb`.`Admnistrador` (`idEspecialista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EventoDesportivo_Modalidade1`
    FOREIGN KEY (`Modalidade_nome`)
    REFERENCES `mydb`.`Modalidade` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Especialista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Especialista` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Especialista` (
  `idEspecialista` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idEspecialista`));


-- -----------------------------------------------------
-- Table `mydb`.`Odd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Odd` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Odd` (
  `idOdd` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(2,4) NOT NULL,
  `Fechada` TINYINT NOT NULL DEFAULT 0,
  `Promoções_idPromoções` INT NOT NULL,
  `Especialista_idEspecialista` INT NOT NULL,
  `EventoDesportivo_idEventoDesportivo` INT NOT NULL,
  PRIMARY KEY (`idOdd`),
  INDEX `fk_Odd_Promoções1_idx` (`Promoções_idPromoções` ASC) VISIBLE,
  INDEX `fk_Odd_Especialista1_idx` (`Especialista_idEspecialista` ASC) VISIBLE,
  INDEX `fk_Odd_EventoDesportivo1_idx` (`EventoDesportivo_idEventoDesportivo` ASC) VISIBLE,
  CONSTRAINT `fk_Odd_Promoções1`
    FOREIGN KEY (`Promoções_idPromoções`)
    REFERENCES `mydb`.`Promoção` (`idPromoções`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Odd_Especialista1`
    FOREIGN KEY (`Especialista_idEspecialista`)
    REFERENCES `mydb`.`Especialista` (`idEspecialista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Odd_EventoDesportivo1`
    FOREIGN KEY (`EventoDesportivo_idEventoDesportivo`)
    REFERENCES `mydb`.`EventoDesportivo` (`idEventoDesportivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aposta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aposta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aposta` (
  `id` INT NOT NULL,
  `Data` DATETIME NULL,
  `valorApostado` DECIMAL(5,2) NOT NULL,
  `Apostador_idUtilizador` INT NOT NULL,
  `Odd_idOdd` INT NOT NULL,
  `Estado` ENUM('Suspensa', 'Fechada', 'Aberta') NOT NULL,
  PRIMARY KEY (`id`, `Apostador_idUtilizador`, `Odd_idOdd`),
  INDEX `fk_Aposta_Apostador_idx` (`Apostador_idUtilizador` ASC) VISIBLE,
  INDEX `fk_Aposta_Odd1_idx` (`Odd_idOdd` ASC) VISIBLE,
  CONSTRAINT `fk_Aposta_Apostador`
    FOREIGN KEY (`Apostador_idUtilizador`)
    REFERENCES `mydb`.`Apostador` (`idUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aposta_Odd1`
    FOREIGN KEY (`Odd_idOdd`)
    REFERENCES `mydb`.`Odd` (`idOdd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estatísticas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estatísticas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estatísticas` (
  `Apostas realizadas` INT NOT NULL DEFAULT 0,
  `Ganhos por apostas` INT NOT NULL DEFAULT 0,
  `Apostas corretas` INT NOT NULL DEFAULT 0,
  `Ganhos Totais` INT NOT NULL DEFAULT 0,
  `Apostas Realizadas visíveis` TINYINT NOT NULL DEFAULT 0,
  `Ganhos por apostas visíveis` TINYINT NOT NULL DEFAULT 0,
  `Apostador_idUtilizador` INT NOT NULL,
  PRIMARY KEY (`Apostador_idUtilizador`),
  CONSTRAINT `fk_Estatísticas_Apostador1`
    FOREIGN KEY (`Apostador_idUtilizador`)
    REFERENCES `mydb`.`Apostador` (`idUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
